name: CI/CD for Next.js to GCP Artifact Registry

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Diperlukan untuk OIDC auth (opsional, tapi bagus untuk security)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev  # Ganti 'us-central1' jika location beda

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            us-central1-docker.pkg.dev/ratu-bio/my-repo/my-app:latest
            us-central1-docker.pkg.dev/ratu-bio/my-repo/my-app:${{ github.sha }}